---
title: "R Notebook"
output: html_notebook
---

Trend analysis of leatherback turtles nesting in Florida, Puerto Rico, and St Croix with Kelly Stewart.

```{r}
rm(list=ls())
library(tidyverse)
library(ggplot2)
library(readr)
library(lubridate)
library(jagsUI)
library(bayesplot)
```

Get data;

```{r}
col.def <- cols(ID = col_integer(),
                year = col_integer(),
                beach = col_character(),
                latitude = col_double(),
                distance = col_double(),
                days_week = col_integer(),
                days_year = col_integer(),
                nests = col_integer())

nest.counts <- read_csv("data/FL_PR_STX.csv", col_types = col.def) %>% 
  mutate(lat_band = ifelse(latitude < 26, 25,
                           ifelse(latitude < 27, 26,
                                  ifelse(latitude < 28, 27,
                                         ifelse(latitude < 29, 28,
                                                ifelse(latitude < 30, 29,
                                                       ifelse(latitude < 31, 30)))))))

```


See what they look like:

```{r}
ggplot(data = nest.counts) +
  geom_point(aes(x = year, y = log(nests+1),
                 color = as.factor(ID))) +
  geom_line(aes(x = year, y = log(nests + 1),
                color = as.factor(ID),
                group = as.factor(ID))) +
  
  facet_wrap( ~ lat_band, nrow = 3) +
  theme(legend.position = "none")
```


Try fitting growth models - we can use the same model as the last paper first. 

```{r}
X <- cbind(nest.counts$distance - median(nest.counts$distance),
           nest.counts$days_week - median(nest.counts$days_week),
           nest.counts$days_year - median(nest.counts$days_year))

nest.counts %>% select(ID, latitude) %>% group_by(ID) %>%
  summarise(latitude = first(latitude)) %>%
  mutate(latc = latitude - mean(latitude),
         latc2 = latc^2) -> lat.dat 

#min(nest.counts$year):max(nest.counts$year)

jags.data <- list(N = length(nest.counts$nests),
                  nbeach = nrow(lat.dat),
                  count = nest.counts$nests,
                  beach = nest.counts$ID,
                  yearc = nest.counts$year/(median(min(nest.counts$year):max(nest.counts$year))),
                  X = X,
                  latc = lat.dat$latc,
                  latc2 = lat.dat$latc2)

MCMC.params <- list(n.samples = 100000,
                    n.burnin = 50000,
                    n.thin = 5,
                    n.chains = 5)

parameters <- c("a0", "a1", "beta", "B.hat", "a1pc",
                "delta1", "delta2",
                "floridapc", "probP", "deviance",
                "Devobs", "Devpred")

MCMC.params$model.file = "models/Model_JAGS_rSlope_rInt_3Covs.txt"

if (!file.exists("RData/JAGS_out_Dist_rSlope_rInt.rds")){
  jm <- jags(data = jags.data,
             #inits = inits,
             parameters.to.save= parameters,
             model.file = MCMC.params$model.file,
             n.chains = MCMC.params$n.chains,
             n.burnin = MCMC.params$n.burnin,
             n.thin = MCMC.params$n.thin,
             n.iter = MCMC.params$n.samples,
             DIC = T, 
             parallel=T)
  
  saveRDS(jm, file = "RData/JAGS_out_Dist_rSlope_rInt.rds")
  
} else {
  jm <- readRDS("RData/JAGS_out_Dist_rSlope_rInt.rds")
}

summary(jm)

mcmc_trace(jm$samples, pars = c("beta[1]", "beta[2]", "beta[3]"))
mcmc_dens(jm$samples, pars = c("beta[1]", "beta[2]", "beta[3]"))
mcmc_trace(jm$samples, pars = c("delta1", "delta2"))
mcmc_dens(jm$samples, pars = c("delta1", "delta2"))

```

These parameters look good but some Rhat stats are too high, according to the output comments. 

```{r}
summary.df <- data.frame(jm$summary) %>% rownames_to_column(var = "parameter") 

summary.df %>% filter(Rhat > 1.01)
```



