---
title: "R Notebook"
output: html_notebook
---

Trend analysis of leatherback turtles nesting in Florida, Puerto Rico, and St Croix with Kelly Stewart.

```{r}
rm(list=ls())
library(tidyverse)
library(ggplot2)
library(readr)
library(lubridate)
library(jagsUI)
library(bayesplot)
```

Get data;

```{r}
col.def <- cols(ID = col_integer(),
                year = col_integer(),
                beach = col_character(),
                latitude = col_double(),
                distance = col_double(),
                days_week = col_integer(),
                days_year = col_integer(),
                nests = col_integer())

nest.counts.FL <- read_csv("data/FL_Sept2020.csv", 
                           col_types = col.def) %>% 
  mutate(beach_f = as.factor(toupper(beach)))

nest.counts.PR <- read_csv("data/PR_Sept2020.csv", 
                           col_types = col.def) %>% 
  mutate(beach_f = as.factor(toupper(beach)))

nest.counts.PR$latitude <- 18.467761

nest.counts.STX <- read_csv("data/STX_Sept2020.csv", 
                            col_types = col.def) %>% 
  mutate(beach_f = as.factor(toupper(beach)))

nest.counts.STX$latitude <- 17.679899

nest.counts <- rbind(nest.counts.FL, nest.counts.PR, nest.counts.STX) %>%
  mutate(ID2 = as.numeric(as.factor(ID)))  %>% 
  mutate(lat_band = ifelse(latitude < 18, 17,
                           ifelse(latitude < 19, 18, 
                                  ifelse(latitude < 26, 25,
                                         ifelse(latitude < 27, 26,
                                                ifelse(latitude < 28, 27,
                                                       ifelse(latitude < 29, 28,
                                                              ifelse(latitude < 30, 29,
                                                                     ifelse(latitude < 31, 30)))))))),
         beach_f = as.factor(toupper(beach)))

```


See what they look like:

```{r}
ggplot(data = nest.counts) +
  geom_point(aes(x = year, y = log(nests+1),
                 color = as.factor(ID))) +
  geom_line(aes(x = year, y = log(nests + 1),
                color = as.factor(ID),
                group = as.factor(ID))) +
  
  facet_wrap( ~ lat_band, nrow = 3) +
  labs(title = "Change in log(abundance) by latitude") +
  theme(legend.position = "none")
```

Plot each beach grouped by latitude band

```{r}
nest.counts %>% 
  filter(lat_band == 17 | lat_band == 18) -> nest.counts.17.18
ggplot(data = nest.counts.17.18) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f)) +
  theme(legend.position = "none") + 
  labs(title = "STX and PR")
```


```{r}
nest.counts %>% filter(lat_band == 25) -> nest.counts.25
ggplot(data = nest.counts.25) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f)) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 25")
```

Too many beaches here so split them into 3 groups.

```{r}
nest.counts %>% filter(lat_band == 26) -> nest.counts.26
unique.IDs <- unique(nest.counts.26$ID)
first.10 <- unique.IDs[1:10]
nest.counts.26 %>% filter(ID %in% first.10) -> nest.counts.26.1

ggplot(data = nest.counts.26.1) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f), ncol = 3) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 26")
```

```{r}
second.10 <- unique.IDs[11:20]
nest.counts.26 %>% filter(ID %in% second.10) -> nest.counts.26.2

ggplot(data = nest.counts.26.2) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f), ncol = 3) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 26")
```

```{r}
beaches.21.31 <- unique.IDs[21:31]
nest.counts.26 %>% filter(ID %in% beaches.21.31) -> nest.counts.26.3

ggplot(data = nest.counts.26.3) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f), ncol = 3) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 26")
```


```{r}
nest.counts %>% filter(lat_band == 27) -> nest.counts.27
ggplot(data = nest.counts.27) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f), ncol = 3) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 27")
```


```{r}
nest.counts %>% filter(lat_band == 28) -> nest.counts.28
ggplot(data = nest.counts.28) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f), ncol = 3) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 28")
```


```{r}
nest.counts %>% filter(lat_band == 29) -> nest.counts.29
ggplot(data = nest.counts.29) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f), ncol = 3) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 29")
```


```{r}
nest.counts %>% filter(lat_band == 30) -> nest.counts.30
ggplot(data = nest.counts.30) +
  geom_point(aes(x = year, y = log(nests+1))) +
  geom_line(aes(x = year, y = log(nests + 1))) +
  facet_wrap( ~ factor(beach_f), ncol = 3) +
  theme(legend.position = "none") + 
  labs(title = "Latitude 30")
```

Time series are different lengths. 

```{r}
nest.counts %>% group_by(beach_f) %>%
  summarise(n = length(year),
            latitude = first(latitude),
            distance = first(distance),
            lat_band = first(lat_band)) -> nest.counts.n

ggplot(data = nest.counts.n) + 
  geom_point(aes(x = lat_band, y = n))
```
